# ElixirChain tool version management with mise
# https://mise.jdx.dev/

[tools]
# Erlang/OTP version
erlang = "28.0.2"

# Elixir version
elixir = "1.18.4"

[env]
# Environment variables for development
MIX_HOME = "~/.mix"
HEX_HOME = "~/.hex"
LANG = "en_US.UTF-8"
LC_ALL = "en_US.UTF-8"


# Elixir/Erlang configuration
ERL_AFLAGS = "-kernel shell_history enabled"
ELIXIR_ERL_OPTIONS = "+fnu"

[tasks.setup]
description = "Set up the development environment"
run = """
echo "Setting up ElixirChain development environment..."
mix local.hex --force
mix local.rebar --force
mix archive.install hex phx_new --force
echo "Setup complete!"
"""

[tasks.mnesia-init]
description = "Initialize Mnesia database for development"
run = """
echo "Mnesia will be initialized automatically when the application starts"
echo "Data will be stored in: ./mnesia_data/"
"""

[settings]
# Use .mise.local.toml for local overrides
legacy_version_file = false
experimental = true

# Version aliases for common commands
[alias.elixir.versions]
"1.16" = "1.16.3"
"1.15" = "1.15.8"
"1.14" = "1.14.5"

[alias.erlang.versions]
"26" = "26.2.5"
"25" = "25.3.2"
"24" = "24.3.4"